# Generated by Django 4.2.3 on 2023-07-31 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="post",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.AddField(
            model_name="blocklist",
            name="server",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="network.foreignserver",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="follower",
            name="server",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="network.foreignserver",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blocklist",
            name="blockedUser",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="follower",
            name="followee_user",
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
