# Generated by Django 4.2.3 on 2023-08-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_rename_username_foreignlike_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foreigncomment",
            name="user",
            field=models.TextField(),
        ),
    ]
